# netlify.toml  ── final version
[build]
  publish  = "site"                       # matches mkdocs.yml’s site_dir
  command  = "pip install -r requirements.txt && python -m mkdocs build --clean"

[build.environment]
  PYTHON_VERSION = "3.11"
